Repository Jackfn96/3DS, pull requests merged in 2022-02, with the labels that each got.

#11 Drive access
  .gitignore
  DDDS/data/.keep
  DDDS/drive.py
  DDDS/logs.py
  Makefile
  notebooks/Jan.ipynb
  notebooks/drive_module_manual.ipynb
  scripts/DDDS-run
  setup.py
Labels: bug, enhancement

#14 HRV signals - notebook update
  notebooks/Simon - HRV signals.ipynb
  notebooks/drive_module_manual.ipynb
Labels: enhancement

#16 Drive access
  .github/workflows/pythonpackage.yml
  DDDS/drive.py
  notebooks/drive_module_manual.ipynb
  requirements.txt
  tests/test_drive.py
Labels: Fix issue

#26 Multiple file download, logs.py renamed to utils.py, progress bar
  DDDS/drive.py
  DDDS/logs.py
  DDDS/utils.py
  notebooks/drive_module_manual.ipynb
  tests/test_drive.py
Labels: enhancement
